# Gitlab CI config for itchy

before_script:
- git submodule foreach git clean -xfd
- git submodule init
- git submodule update

stages:
- build
- deploy

binaries:
  stage: build
  script:
  - "mkdir itchy"
  - "npm install"
  - "stack --no-terminal build --test --copy-bins --local-bin-path itchy"
  artifacts:
    paths:
    - itchy
    expire_in: 1 week
  tags:
  - haskellstack
  - linux
  - x64

deploy:
  stage: deploy
  dependencies:
  - binaries
  script:
  - "cp itchy/itchy-runner containers/runner/"
  - "cp itchy/itchyd containers/itchyd/"
  - >-
    ansible-playbook
    -i "$DEPLOY_HOSTS,"
    containers/update.yml
  tags:
  - linux
  - x64
  only:
  - master
