resolver: deps/flaw/integer-simple-snapshot.yaml

packages:
- .
- location: deps/flaw
  subdirs:
  - flaw-base
  - flaw-lmdb
  extra-dep: true

extra-deps:
- wai-routes-0.10.1

ghc-options:
  "$locals": -threaded -with-rtsopts=-N -Wall -fno-warn-unsupported-calling-conventions -Wno-tabs
