resolver:
  name: integer-simple-snapshot
  location: deps/flaw/integer-simple-snapshot.yaml

packages:
- .
- location: deps/flaw
  subdirs:
  - flaw-base
  - flaw-lmdb
  extra-dep: true

ghc-options:
  "*": -threaded -with-rtsopts=-N -Wall -fno-warn-unsupported-calling-conventions -Wno-tabs
