version: "3.2"

services:
  itchyd:
    build:
      context: .
    image: itchyd:latest
    ports:
    - "127.0.0.1:8888:8888"
    restart: on-failure
    volumes:
    - "/opt/itchy:/var/itchy"
    - "/var/run/docker.sock:/var/run/docker.sock"
